--- 
pid: tmp/pids/thin.pid
log: log/thin.log
timeout: 30
max_conns: 1024
port: 4567
max_persistent_conns: 512
environment: development
chdir: /var/www/lachstock/current
require: []
rackup: config.ru

daemonize: true
address: 0.0.0.0
